// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Falconic.Skp.Api.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class UpdateLastCommunication
    {
        /// <summary>
        /// Initializes a new instance of the UpdateLastCommunication class.
        /// </summary>
        public UpdateLastCommunication()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UpdateLastCommunication class.
        /// </summary>
        public UpdateLastCommunication(System.DateTime lastCommunication)
        {
            LastCommunication = lastCommunication;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastCommunication")]
        public System.DateTime LastCommunication { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
