// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Falconic.Skp.Api.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class LastCommunicationResult
    {
        /// <summary>
        /// Initializes a new instance of the LastCommunicationResult class.
        /// </summary>
        public LastCommunicationResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the LastCommunicationResult class.
        /// </summary>
        public LastCommunicationResult(System.DateTime? lastCommunication = default(System.DateTime?))
        {
            LastCommunication = lastCommunication;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastCommunication")]
        public System.DateTime? LastCommunication { get; set; }

    }
}
