// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Falconic.Skp.Api.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PreferredLocationFractionDto
    {
        /// <summary>
        /// Initializes a new instance of the PreferredLocationFractionDto
        /// class.
        /// </summary>
        public PreferredLocationFractionDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PreferredLocationFractionDto
        /// class.
        /// </summary>
        public PreferredLocationFractionDto(int? locationId = default(int?), System.Guid? fractionId = default(System.Guid?), double? latitude = default(double?), double? longitude = default(double?))
        {
            LocationId = locationId;
            FractionId = fractionId;
            Latitude = latitude;
            Longitude = longitude;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "locationId")]
        public int? LocationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fractionId")]
        public System.Guid? FractionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "latitude")]
        public double? Latitude { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "longitude")]
        public double? Longitude { get; set; }

    }
}
