// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Falconic.Skp.Api.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class StoreContainerStatus
    {
        /// <summary>
        /// Initializes a new instance of the StoreContainerStatus class.
        /// </summary>
        public StoreContainerStatus()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the StoreContainerStatus class.
        /// </summary>
        public StoreContainerStatus(string simCardNumber, int? locationId = default(int?), IList<StatusMessageDto> statusMessages = default(IList<StatusMessageDto>))
        {
            LocationId = locationId;
            SimCardNumber = simCardNumber;
            StatusMessages = statusMessages;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "locationId")]
        public int? LocationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "simCardNumber")]
        public string SimCardNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "statusMessages")]
        public IList<StatusMessageDto> StatusMessages { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (SimCardNumber == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "SimCardNumber");
            }
            if (SimCardNumber != null)
            {
                if (SimCardNumber.Length > 255)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "SimCardNumber", 255);
                }
                if (SimCardNumber.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "SimCardNumber", 0);
                }
            }
            if (StatusMessages != null)
            {
                foreach (var element in StatusMessages)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
