// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Falconic.Skp.Api.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ContainerParamsDto
    {
        /// <summary>
        /// Initializes a new instance of the ContainerParamsDto class.
        /// </summary>
        public ContainerParamsDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ContainerParamsDto class.
        /// </summary>
        public ContainerParamsDto(int id, int readPointer, int writePointer, int? operatorId = default(int?), string internalIdentNumber = default(string), string deviceNumber = default(string), string simCardNumber = default(string), string gsmNumber = default(string), string firmwareVersion = default(string), bool? retrofit = default(bool?), PreferredLocationFractionDto preferredLocation = default(PreferredLocationFractionDto), PreferredLocationFractionDto lastLocation = default(PreferredLocationFractionDto))
        {
            Id = id;
            OperatorId = operatorId;
            InternalIdentNumber = internalIdentNumber;
            DeviceNumber = deviceNumber;
            SimCardNumber = simCardNumber;
            GsmNumber = gsmNumber;
            FirmwareVersion = firmwareVersion;
            Retrofit = retrofit;
            ReadPointer = readPointer;
            WritePointer = writePointer;
            PreferredLocation = preferredLocation;
            LastLocation = lastLocation;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "operatorId")]
        public int? OperatorId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "internalIdentNumber")]
        public string InternalIdentNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deviceNumber")]
        public string DeviceNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "simCardNumber")]
        public string SimCardNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "gsmNumber")]
        public string GsmNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "firmwareVersion")]
        public string FirmwareVersion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "retrofit")]
        public bool? Retrofit { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "readPointer")]
        public int ReadPointer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "writePointer")]
        public int WritePointer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "preferredLocation")]
        public PreferredLocationFractionDto PreferredLocation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastLocation")]
        public PreferredLocationFractionDto LastLocation { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
