// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Falconic.Skp.Api.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CreateInsertionTransaction
    {
        /// <summary>
        /// Initializes a new instance of the CreateInsertionTransaction class.
        /// </summary>
        public CreateInsertionTransaction()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateInsertionTransaction class.
        /// </summary>
        public CreateInsertionTransaction(System.DateTime timestamp, int operatorId, int cardId, int containerId, int locationId, double weight)
        {
            Timestamp = timestamp;
            OperatorId = operatorId;
            CardId = cardId;
            ContainerId = containerId;
            LocationId = locationId;
            Weight = weight;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timestamp")]
        public System.DateTime Timestamp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "operatorId")]
        public int OperatorId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cardId")]
        public int CardId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "containerId")]
        public int ContainerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "locationId")]
        public int LocationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "weight")]
        public double Weight { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
