// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Falconic.Skp.Api.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class HasCardAccessToLocationFractionByCardUuid
    {
        /// <summary>
        /// Initializes a new instance of the
        /// HasCardAccessToLocationFractionByCardUuid class.
        /// </summary>
        public HasCardAccessToLocationFractionByCardUuid()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// HasCardAccessToLocationFractionByCardUuid class.
        /// </summary>
        public HasCardAccessToLocationFractionByCardUuid(string cardUuid, int operatorId, int locationId)
        {
            CardUuid = cardUuid;
            OperatorId = operatorId;
            LocationId = locationId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cardUuid")]
        public string CardUuid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "operatorId")]
        public int OperatorId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "locationId")]
        public int LocationId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (CardUuid == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "CardUuid");
            }
            if (CardUuid != null)
            {
                if (CardUuid.Length > 255)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "CardUuid", 255);
                }
                if (CardUuid.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "CardUuid", 0);
                }
            }
        }
    }
}
