// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Falconic.Skp.Api.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OperatorParamsDto
    {
        /// <summary>
        /// Initializes a new instance of the OperatorParamsDto class.
        /// </summary>
        public OperatorParamsDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OperatorParamsDto class.
        /// </summary>
        /// <param name="transactionOfflineMode">Possible values include:
        /// 'Allow', 'Forbid'</param>
        /// <param name="balanceMode">Possible values include: 'OnlineBalance',
        /// 'OfflineBalance'</param>
        public OperatorParamsDto(int operatorId, int currencyId, TransactionOfflineMode transactionOfflineMode, BalanceMode balanceMode, string operatorName = default(string), string languageCode = default(string), string timezoneId = default(string))
        {
            OperatorId = operatorId;
            OperatorName = operatorName;
            CurrencyId = currencyId;
            LanguageCode = languageCode;
            TimezoneId = timezoneId;
            TransactionOfflineMode = transactionOfflineMode;
            BalanceMode = balanceMode;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "operatorId")]
        public int OperatorId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "operatorName")]
        public string OperatorName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "currencyId")]
        public int CurrencyId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "languageCode")]
        public string LanguageCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timezoneId")]
        public string TimezoneId { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Allow', 'Forbid'
        /// </summary>
        [JsonProperty(PropertyName = "transactionOfflineMode")]
        public TransactionOfflineMode TransactionOfflineMode { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'OnlineBalance',
        /// 'OfflineBalance'
        /// </summary>
        [JsonProperty(PropertyName = "balanceMode")]
        public BalanceMode BalanceMode { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
