// <auto-generated />

namespace Falconic.Skp.Api.Client.Models
{
    using Falconic.Skp;
    using Falconic.Skp.Api;
    using Falconic.Skp.Api.Client;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GetSkpLocations
    {
        /// <summary>
        /// Initializes a new instance of the GetSkpLocations class.
        /// </summary>
        public GetSkpLocations()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GetSkpLocations class.
        /// </summary>
        public GetSkpLocations(double? minLatitude = default(double?), double? maxLatitude = default(double?), double? minLongitude = default(double?), double? maxLongitude = default(double?))
        {
            MinLatitude = minLatitude;
            MaxLatitude = maxLatitude;
            MinLongitude = minLongitude;
            MaxLongitude = maxLongitude;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "minLatitude")]
        public double? MinLatitude { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "maxLatitude")]
        public double? MaxLatitude { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "minLongitude")]
        public double? MinLongitude { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "maxLongitude")]
        public double? MaxLongitude { get; set; }

    }
}
