// <auto-generated />

namespace Falconic.Skp.Api.Client.Models
{
    using Falconic.Skp;
    using Falconic.Skp.Api;
    using Falconic.Skp.Api.Client;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class LocationParamsDto
    {
        /// <summary>
        /// Initializes a new instance of the LocationParamsDto class.
        /// </summary>
        public LocationParamsDto()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the LocationParamsDto class.
        /// </summary>
        public LocationParamsDto(string name = default(string), System.DateTime? nightlockStart = default(System.DateTime?), System.DateTime? nightlockStop = default(System.DateTime?), double? accessLimit = default(double?), double? pricePerOneHundredKilo = default(double?), bool? emptyingIsMaintained = default(bool?), int? machineUtilization = default(int?))
        {
            Name = name;
            NightlockStart = nightlockStart;
            NightlockStop = nightlockStop;
            AccessLimit = accessLimit;
            PricePerOneHundredKilo = pricePerOneHundredKilo;
            EmptyingIsMaintained = emptyingIsMaintained;
            MachineUtilization = machineUtilization;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "nightlockStart")]
        public System.DateTime? NightlockStart { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "nightlockStop")]
        public System.DateTime? NightlockStop { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "accessLimit")]
        public double? AccessLimit { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pricePerOneHundredKilo")]
        public double? PricePerOneHundredKilo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "emptyingIsMaintained")]
        public bool? EmptyingIsMaintained { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "machineUtilization")]
        public int? MachineUtilization { get; set; }

    }
}
