// <auto-generated />

namespace Falconic.Skp.Api.Client.Models
{
    using Falconic.Skp;
    using Falconic.Skp.Api;
    using Falconic.Skp.Api.Client;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SkpContainerDto
    {
        /// <summary>
        /// Initializes a new instance of the SkpContainerDto class.
        /// </summary>
        public SkpContainerDto()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SkpContainerDto class.
        /// </summary>
        public SkpContainerDto(int? containerId = default(int?), System.DateTime? lastCommunication = default(System.DateTime?), string deviceNumber = default(string), string simCardNumber = default(string), int? operatorId = default(int?))
        {
            ContainerId = containerId;
            LastCommunication = lastCommunication;
            DeviceNumber = deviceNumber;
            SimCardNumber = simCardNumber;
            OperatorId = operatorId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "containerId")]
        public int? ContainerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastCommunication")]
        public System.DateTime? LastCommunication { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deviceNumber")]
        public string DeviceNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "simCardNumber")]
        public string SimCardNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "operatorId")]
        public int? OperatorId { get; set; }

    }
}
