// <auto-generated />

namespace Falconic.Skp.Api.Client.Models
{
    using Falconic.Skp;
    using Falconic.Skp.Api;
    using Falconic.Skp.Api.Client;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class StatusMessageDto
    {
        /// <summary>
        /// Initializes a new instance of the StatusMessageDto class.
        /// </summary>
        public StatusMessageDto()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the StatusMessageDto class.
        /// </summary>
        public StatusMessageDto(int? code = default(int?), double? fillState = default(double?), System.DateTime? timestamp = default(System.DateTime?), bool? shouldNotifyUser = default(bool?))
        {
            Code = code;
            FillState = fillState;
            Timestamp = timestamp;
            ShouldNotifyUser = shouldNotifyUser;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "code")]
        public int? Code { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fillState")]
        public double? FillState { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timestamp")]
        public System.DateTime? Timestamp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "shouldNotifyUser")]
        public bool? ShouldNotifyUser { get; set; }

    }
}
