// <auto-generated />

namespace Falconic.Skp.Api.Client.Models
{
    using Falconic.Skp;
    using Falconic.Skp.Api;
    using Falconic.Skp.Api.Client;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class UpdateContainer
    {
        /// <summary>
        /// Initializes a new instance of the UpdateContainer class.
        /// </summary>
        public UpdateContainer()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UpdateContainer class.
        /// </summary>
        public UpdateContainer(int? containerId = default(int?))
        {
            ContainerId = containerId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "containerId")]
        public int? ContainerId { get; set; }

    }
}
