// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Falconic.Skp.Api.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ContainerHardwareInformationDto
    {
        /// <summary>
        /// Initializes a new instance of the ContainerHardwareInformationDto
        /// class.
        /// </summary>
        public ContainerHardwareInformationDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ContainerHardwareInformationDto
        /// class.
        /// </summary>
        public ContainerHardwareInformationDto(int operatingMinutes, int numberOfStartings, int gsmSignalStrength, string dataConnection = default(string), string firmwareVersion = default(string), string targetFirmwareVersion = default(string), System.DateTime? targetFirmwareUpdateDate = default(System.DateTime?))
        {
            OperatingMinutes = operatingMinutes;
            NumberOfStartings = numberOfStartings;
            GsmSignalStrength = gsmSignalStrength;
            DataConnection = dataConnection;
            FirmwareVersion = firmwareVersion;
            TargetFirmwareVersion = targetFirmwareVersion;
            TargetFirmwareUpdateDate = targetFirmwareUpdateDate;
            CustomInit();
        }
        /// <summary>
        /// Static constructor for ContainerHardwareInformationDto class.
        /// </summary>
        static ContainerHardwareInformationDto()
        {
            FirmwareType = "Presscontrol";
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "operatingMinutes")]
        public int OperatingMinutes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numberOfStartings")]
        public int NumberOfStartings { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "gsmSignalStrength")]
        public int GsmSignalStrength { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dataConnection")]
        public string DataConnection { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "firmwareVersion")]
        public string FirmwareVersion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "targetFirmwareVersion")]
        public string TargetFirmwareVersion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "targetFirmwareUpdateDate")]
        public System.DateTime? TargetFirmwareUpdateDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "firmwareType")]
        public static string FirmwareType { get; private set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
