// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Falconic.Skp.Api.Client.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for ContactMethod.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ContactMethod
    {
        [EnumMember(Value = "Email")]
        Email,
        [EnumMember(Value = "Sms")]
        Sms
    }
    internal static class ContactMethodEnumExtension
    {
        internal static string ToSerializedValue(this ContactMethod? value)
        {
            return value == null ? null : ((ContactMethod)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this ContactMethod value)
        {
            switch( value )
            {
                case ContactMethod.Email:
                    return "Email";
                case ContactMethod.Sms:
                    return "Sms";
            }
            return null;
        }

        internal static ContactMethod? ParseContactMethod(this string value)
        {
            switch( value )
            {
                case "Email":
                    return ContactMethod.Email;
                case "Sms":
                    return ContactMethod.Sms;
            }
            return null;
        }
    }
}
