// <auto-generated />

namespace Falconic.Skp.Api.Client.Models
{
    using Falconic.Skp;
    using Falconic.Skp.Api;
    using Falconic.Skp.Api.Client;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ContainerParamsDto
    {
        /// <summary>
        /// Initializes a new instance of the ContainerParamsDto class.
        /// </summary>
        public ContainerParamsDto()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ContainerParamsDto class.
        /// </summary>
        public ContainerParamsDto(int? operatorId = default(int?), string internalIdentNumber = default(string), string deviceNumber = default(string), string simCardNumber = default(string), string gsmNumber = default(string), string firmwareVersion = default(string), int? readPointer = default(int?), int? writePointer = default(int?))
        {
            OperatorId = operatorId;
            InternalIdentNumber = internalIdentNumber;
            DeviceNumber = deviceNumber;
            SimCardNumber = simCardNumber;
            GsmNumber = gsmNumber;
            FirmwareVersion = firmwareVersion;
            ReadPointer = readPointer;
            WritePointer = writePointer;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "operatorId")]
        public int? OperatorId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "internalIdentNumber")]
        public string InternalIdentNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deviceNumber")]
        public string DeviceNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "simCardNumber")]
        public string SimCardNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "gsmNumber")]
        public string GsmNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "firmwareVersion")]
        public string FirmwareVersion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "readPointer")]
        public int? ReadPointer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "writePointer")]
        public int? WritePointer { get; set; }

    }
}
