// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Falconic.Skp.Api.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CreateInsertionResult
    {
        /// <summary>
        /// Initializes a new instance of the CreateInsertionResult class.
        /// </summary>
        public CreateInsertionResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateInsertionResult class.
        /// </summary>
        public CreateInsertionResult(double chargedAmount, double? newCurrentBalance = default(double?))
        {
            ChargedAmount = chargedAmount;
            NewCurrentBalance = newCurrentBalance;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "chargedAmount")]
        public double ChargedAmount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "newCurrentBalance")]
        public double? NewCurrentBalance { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
