// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Falconic.Skp.Api.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class HasCardAccessToLocationFractionByCustomerNumber
    {
        /// <summary>
        /// Initializes a new instance of the
        /// HasCardAccessToLocationFractionByCustomerNumber class.
        /// </summary>
        public HasCardAccessToLocationFractionByCustomerNumber()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// HasCardAccessToLocationFractionByCustomerNumber class.
        /// </summary>
        public HasCardAccessToLocationFractionByCustomerNumber(int customerNumber, int operatorId, int locationId)
        {
            CustomerNumber = customerNumber;
            OperatorId = operatorId;
            LocationId = locationId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customerNumber")]
        public int CustomerNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "operatorId")]
        public int OperatorId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "locationId")]
        public int LocationId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
