// <auto-generated />

namespace Falconic.Skp.Api.Client.Models
{
    using Falconic.Skp;
    using Falconic.Skp.Api;
    using Falconic.Skp.Api.Client;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for SkpContactMethod.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum SkpContactMethod
    {
        [EnumMember(Value = "Email")]
        Email,
        [EnumMember(Value = "Sms")]
        Sms
    }
}
