// <auto-generated />

namespace Falconic.Skp.Api.Client.Models
{
    using Falconic.Skp;
    using Falconic.Skp.Api;
    using Falconic.Skp.Api.Client;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SkpNotificationContactDto
    {
        /// <summary>
        /// Initializes a new instance of the SkpNotificationContactDto class.
        /// </summary>
        public SkpNotificationContactDto()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SkpNotificationContactDto class.
        /// </summary>
        /// <param name="contactMethod">Possible values include: 'Email',
        /// 'Sms'</param>
        public SkpNotificationContactDto(string contact = default(string), ContactMethod? contactMethod = default(ContactMethod?))
        {
            Contact = contact;
            ContactMethod = contactMethod;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contact")]
        public string Contact { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Email', 'Sms'
        /// </summary>
        [JsonProperty(PropertyName = "contactMethod")]
        public ContactMethod? ContactMethod { get; set; }

    }
}
