// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Falconic.Skp.Api.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SkpNotificationContactDto
    {
        /// <summary>
        /// Initializes a new instance of the SkpNotificationContactDto class.
        /// </summary>
        public SkpNotificationContactDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SkpNotificationContactDto class.
        /// </summary>
        /// <param name="contactMethod">Possible values include: 'Email',
        /// 'Sms'</param>
        public SkpNotificationContactDto(ContactMethod contactMethod, string contact = default(string))
        {
            Contact = contact;
            ContactMethod = contactMethod;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contact")]
        public string Contact { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Email', 'Sms'
        /// </summary>
        [JsonProperty(PropertyName = "contactMethod")]
        public ContactMethod ContactMethod { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
