// <auto-generated />

namespace Falconic.Skp.Api.Client.Models
{
    using Falconic.Skp;
    using Falconic.Skp.Api;
    using Falconic.Skp.Api.Client;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SkpStatusTypeDto
    {
        /// <summary>
        /// Initializes a new instance of the SkpStatusTypeDto class.
        /// </summary>
        public SkpStatusTypeDto()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SkpStatusTypeDto class.
        /// </summary>
        public SkpStatusTypeDto(int? id = default(int?), string name = default(string))
        {
            Id = id;
            Name = name;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

    }
}
