// <auto-generated />

namespace Falconic.Skp.Api.Client.Models
{
    using Falconic.Skp;
    using Falconic.Skp.Api;
    using Falconic.Skp.Api.Client;
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class StatusTypeIdsModel
    {
        /// <summary>
        /// Initializes a new instance of the StatusTypeIdsModel class.
        /// </summary>
        public StatusTypeIdsModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the StatusTypeIdsModel class.
        /// </summary>
        public StatusTypeIdsModel(IList<int?> statusTypeIds)
        {
            StatusTypeIds = statusTypeIds;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "statusTypeIds")]
        public IList<int?> StatusTypeIds { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (StatusTypeIds == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "StatusTypeIds");
            }
        }
    }
}
