// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Falconic.Skp.Api.Client.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for TransactionOfflineMode.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TransactionOfflineMode
    {
        [EnumMember(Value = "Allow")]
        Allow,
        [EnumMember(Value = "Forbid")]
        Forbid
    }
    internal static class TransactionOfflineModeEnumExtension
    {
        internal static string ToSerializedValue(this TransactionOfflineMode? value)
        {
            return value == null ? null : ((TransactionOfflineMode)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this TransactionOfflineMode value)
        {
            switch( value )
            {
                case TransactionOfflineMode.Allow:
                    return "Allow";
                case TransactionOfflineMode.Forbid:
                    return "Forbid";
            }
            return null;
        }

        internal static TransactionOfflineMode? ParseTransactionOfflineMode(this string value)
        {
            switch( value )
            {
                case "Allow":
                    return TransactionOfflineMode.Allow;
                case "Forbid":
                    return TransactionOfflineMode.Forbid;
            }
            return null;
        }
    }
}
