// <auto-generated />

namespace Falconic.Skp.Api.Client.Models
{
    using Falconic.Skp;
    using Falconic.Skp.Api;
    using Falconic.Skp.Api.Client;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class UpdateLastCommunication
    {
        /// <summary>
        /// Initializes a new instance of the UpdateLastCommunication class.
        /// </summary>
        public UpdateLastCommunication()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UpdateLastCommunication class.
        /// </summary>
        public UpdateLastCommunication(System.DateTime? lastCommunication = default(System.DateTime?))
        {
            LastCommunication = lastCommunication;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastCommunication")]
        public System.DateTime? LastCommunication { get; set; }

    }
}
